### PR TITLE
Add public API to iterate over L2/L3 data

### LINKED ISSUE #208: Add public API to iterate over L2/L3 data
Currently the `serum_dex` crate does not expose any public API to iterate over the order book. It is possible to do it by repeatedly calling `find_min/max()` and `remove_by_key()` on the slap as it is done by the matching engine, but this depends on implementation detail and require unnecessary mutation. 

I saw that the `serum-ts` library exposes a `slab.items()` generator as well as a `getL2` method. Can we add a similar functionality to the Rust crate?

I can implement it if the request is approved.

### PR DESCRIPTION
**Pull request by tommyip**
Fixes #208

### CODE REVIEW

**Comment by tommyip** [comment]
Usage:
```rust
use serum_dex::utils::{OrderBook, Level};

let bids_slab = market_state.load_bids_mut(&bids_account_info)?;
let orderbook = OrderBook::new(Side::Bid, &bids_slab);

let eg1 = orderbook.levels();
let eg2: Vec<Level> = orderbook.levels().take(10).collect();
```

**Comment by dovahcrow** [comment]
Can we have Default derived for Level?

**Comment by tommyip** [comment]
Added. The maintainers doesn't seem to be interested in this PR though.

**Comment by dovahcrow** [comment]
> Added. The maintainers doesn't seem to be interested in this PR though.

Thank you! Yeah I hope this PR can be merged soon. I've been using your branch for a long time. It is very useful! I appreciate your work here.

**Pull request closed without merging**
